accountapp/urls.py
from django.urls import path
from accountapp.views import start, test, upload
from django.conf import settings
from django.conf.urls.static import static

app_name = 'hello_world'

urlpatterns = [
    path('start/', start, name='start'),
    path('test/', test, name='test'),
    path('upload/', upload, name='upload'),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hackathonproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls'))
]

accountapp/models.py
from django.db import models

# Create your models here.

class Video(models.Model):
    caption=models.CharField(max_length=100)
    video=models.FileField(upload_to="video/%y")
    def __str__(self):
        return self.caption

accountapp/views.py
from django.shortcuts import render

from .models import Video

# Create your views here.
from django.views.generic import ListView


def start(request):
    return render(request, 'accountapp/index.html')

def test(request):
    return render(request, 'accountapp/test.html')

def upload(request):
    if request.method == 'post':
        upload_file = request.FiLES['video']
    return render(request, 'accountapp/modals.html')

accountapp/templates/accountapp/base.html
<!DOCTYPE html>
<meta charset="utf-8">

<html>

{% load static %}

<head>
    <title>임정박이 홈페이지</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
        .button {
            font-size: 100px;
            padding: 40px 40px;
            width: 250px;
            border-radius: 50%;
        }

        body {
            {#background-image:url("{% static 'test.jpg' %}");#}
            background-color: darkgrey;
        }
    </style>

</head>

<body>

<div style="padding: 30px; text-align: center">
    <h1>임정박이 홈페이지</h1>
</div>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="./index.html">Do It Django</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="./index.html">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="./blog_list.html">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="./about_me.html">About Me</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown link
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">Log In</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div style="padding-top: 5rem; text-align: center">
    <h3>부트스트랩으로 네비게이션바를 추가하자</h3>
    <h3>부트스랩으로 버튼을 꾸미자</h3>

    <p>제출 버튼을 누르면 함수를 실행하고 return 값을 출력해 주는 것을 만들어 보고 싶다.</p>
</div>

<br>

<div style="padding-left: 600px; padding-right: 600px" >
    <div class="shadow-lg p-3 mb-5 bg-body rounded">
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title" style="text-align: center;">Get training</h5>
            <p class="card-text" style="text-align: center">.......</p>
            <a href="{% url 'hello_world:test' %}" class="btn btn-primary" style="padding-left: 5rem; padding-right: 5rem;">let's start</a>
        </div>
    </div>
</div>
</div>
</div>

</body>

</html>

accountapp/templates/accountapp/index.html
<!doctype html>

{% load static %}
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Cover Template · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/cover/">


    <!-- Bootstrap core CSS -->
    <link href="./css/bootstrap.min.css" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="./css/cover.css" rel="stylesheet">
    {# BOOTSTRAP LINK #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


</head>
<body class="d-flex h-100 text-center text-white bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div  style="padding: 30px">
            <h4 class="float-md-start mb-0" style="color: orange">
                <img src="https://codelion-curriculum.s3.ap-northeast-2.amazonaws.com/images/oopy+logo_final.png" alt=""
                     style="display: inline; width: 100px;">
                꿈의 시작, 광주인공지능사관학교</h4>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link active" aria-current="page" href="#">
                    <button type="button" class="btn btn-secondary">Team info</button>
                </a>
                <a class="nav-link active" aria-current="page" href="#">
                    <button type="button" class="btn btn-secondary">Service</button>
                </a>
                <a class="nav-link active" aria-current="page" href="#">
                    <button type="button" class="btn btn-secondary">Etc</button>
                </a>
            </nav>
        </div>
    </header>

    <main class="px-3">
        <h1 style="color: yellow; font-weight: bold">
            <img src="{% static 'parking2.png' %}" alt="" style="width: 150px; display: inline-block ">
            My Parking Space X  </h1>
        <br/>
        <br/>
        <h1 >주차공간 실시간 정보 제공 서비스</h1>
        <br>
        <h6>주차장 자리 검색, 헤메지 마세요. MPS.X로 빠르게 찾아보세요. </h6>
        <p class="lead">
            <br/> <br/>
            <a href="{% url 'hello_world:upload' %}" class="btn btn-lg btn-block fw-bold border-white bg-white">let's
                start</a>
        </p>
    </main>

    <footer class="mt-auto text-white-50">
        <p>From 임정박이 <a href="https://getbootstrap.com/" class="text-white">X KODE</a>,
        <p>Github adress : <a href="https://github.com/sunghak2234/hackathonproject" class="text-white">https://github.com/sunghak2234/hackathonproject</a>

    </footer>
</div>


</body>
</html>

accountapp/templates/accountapp/modals.html
<!doctype html>
    {% load static %}


<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Modals · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/modals/">


    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
    {# BOOTSTRAP LINK #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <style>
         body {
        background-image:url("{% static 'test3.jpg' %}");
        background-size:100%;
        {#background-color: darkgrey;#}
        }
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="modals.css" rel="stylesheet">
</head>
<body>


<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="bootstrap" viewBox="0 0 118 94">
        <title>Bootstrap</title>
        <path fill-rule="evenodd" clip-rule="evenodd"
              d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
    </symbol>

    <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>

    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>

    <symbol id="check2-circle" viewBox="0 0 16 16">
        <path d="M2.5 8a5.5 5.5 0 0 1 8.25-4.764.5.5 0 0 0 .5-.866A6.5 6.5 0 1 0 14.5 8a.5.5 0 0 0-1 0 5.5 5.5 0 1 1-11 0z"/>
        <path d="M15.354 3.354a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l7-7z"/>
    </symbol>

    <symbol id="bookmark-star" viewBox="0 0 16 16">
        <path d="M7.84 4.1a.178.178 0 0 1 .32 0l.634 1.285a.178.178 0 0 0 .134.098l1.42.206c.145.021.204.2.098.303L9.42 6.993a.178.178 0 0 0-.051.158l.242 1.414a.178.178 0 0 1-.258.187l-1.27-.668a.178.178 0 0 0-.165 0l-1.27.668a.178.178 0 0 1-.257-.187l.242-1.414a.178.178 0 0 0-.05-.158l-1.03-1.001a.178.178 0 0 1 .098-.303l1.42-.206a.178.178 0 0 0 .134-.098L7.84 4.1z"/>
        <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
    </symbol>

    <symbol id="grid-fill" viewBox="0 0 16 16">
        <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zm8 0A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm-8 8A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm8 0A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3z"/>
    </symbol>

    <symbol id="stars" viewBox="0 0 16 16">
        <path d="M7.657 6.247c.11-.33.576-.33.686 0l.645 1.937a2.89 2.89 0 0 0 1.829 1.828l1.936.645c.33.11.33.576 0 .686l-1.937.645a2.89 2.89 0 0 0-1.828 1.829l-.645 1.936a.361.361 0 0 1-.686 0l-.645-1.937a2.89 2.89 0 0 0-1.828-1.828l-1.937-.645a.361.361 0 0 1 0-.686l1.937-.645a2.89 2.89 0 0 0 1.828-1.828l.645-1.937zM3.794 1.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387A1.734 1.734 0 0 0 4.593 5.69l-.387 1.162a.217.217 0 0 1-.412 0L3.407 5.69A1.734 1.734 0 0 0 2.31 4.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387A1.734 1.734 0 0 0 3.407 2.31l.387-1.162zM10.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732L9.1 2.137a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L10.863.1z"/>
    </symbol>

    <symbol id="film" viewBox="0 0 16 16">
        <path d="M0 1a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V1zm4 0v6h8V1H4zm8 8H4v6h8V9zM1 1v2h2V1H1zm2 3H1v2h2V4zM1 7v2h2V7H1zm2 3H1v2h2v-2zm-2 3v2h2v-2H1zM15 1h-2v2h2V1zm-2 3v2h2V4h-2zm2 3h-2v2h2V7zm-2 3v2h2v-2h-2zm2 3h-2v2h2v-2z"/>
    </symbol>

    <symbol id="github" viewBox="0 0 16 16">
        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
    </symbol>

    <symbol id="twitter" viewBox="0 0 16 16">
        <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
    </symbol>

    <symbol id="facebook" viewBox="0 0 16 16">
        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
    </symbol>
</svg>

<div class="b-example-divider"></div>

<div class="modal modal-tour position-static d-block bg-secondary py-5" tabindex="-1" role="dialog" id="modalTour">
    <div class="modal-dialog" role="document">
        <div class="modal-content rounded-6 shadow">
            <div class="modal-body p-5" style="margin: auto; padding: 5px">
                <h2 class="fw-bold mb-0" style="text-align: center">Input Data</h2>
                <br>
                <br>
                <ul class="d-grid gap-4 my-5 list-unstyled">

                    <li class="d-flex gap-4">
                        <svg class="bi text-primary flex-shrink-0" width="48" height="48">
                            <use xlink:href="#film"/>
                        </svg>
                        <div style="margin:7px">
                            <h5 class="mb-0">Video embeds</h5>
                            <form action="{% url 'hello_world:test' %}"
                                  method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="d-grid gap-2">
                                    <input class="btn btn-light" type="file">
                                </div>
                            </form>
                        </div>
                    </li>
                </ul>
                <br>
                <a href="{% url 'hello_world:test' %}"><input style="height: 55px" type="submit" class="btn btn-lg btn-primary mt-5 w-100"></a>
                <br> <br> <br>


                </button>
            </div>
        </div>
    </div>
</div>

<div class="b-example-divider"></div>

<div class="modal modal-signin position-static d-block bg-secondary py-5" tabindex="-1" role="dialog" id="modalSignin">
    <div class="modal-dialog" role="document">
        <div class="modal-content rounded-5 shadow">
            <div class="modal-header p-5 pb-4 border-bottom-0">
                <!-- <h5 class="modal-title">Modal title</h5> -->
                <h2 class="fw-bold mb-0">Sign up for free</h2>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body p-5 pt-0">
                <form class="">
                    <div class="form-floating mb-3">
                        <input type="email" class="form-control rounded-4" id="floatingInput"
                               placeholder="name@example.com">
                        <label for="floatingInput">Email address</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control rounded-4" id="floatingPassword"
                               placeholder="Password">
                        <label for="floatingPassword">Password</label>
                    </div>
                    <button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Sign up</button>
                    <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
                    <hr class="my-4">
                    <h2 class="fs-5 fw-bold mb-3">Or use a third-party</h2>
                    <button class="w-100 py-2 mb-2 btn btn-outline-dark rounded-4" type="submit">
                        <svg class="bi me-1" width="16" height="16">
                            <use xlink:href="#twitter"/>
                        </svg>
                        Sign up with Twitter
                    </button>
                    <button class="w-100 py-2 mb-2 btn btn-outline-primary rounded-4" type="submit">
                        <svg class="bi me-1" width="16" height="16">
                            <use xlink:href="#facebook"/>
                        </svg>
                        Sign up with Facebook
                    </button>
                    <button class="w-100 py-2 mb-2 btn btn-outline-secondary rounded-4" type="submit">
                        <svg class="bi me-1" width="16" height="16">
                            <use xlink:href="#github"/>
                        </svg>
                        Sign up with GitHub
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="b-example-divider"></div>


<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

<script language="javascript">

</script>

</body>
</html>

accountapp/templates/accountapp/start.html
{% extends 'base.html' %}


{% block content %}


    <div style="padding-top: 5rem; text-align: center">
        <p>제출 버튼을 누르면 함수를 실행하고 return 값을 출력해 주는 것을 만들어 보고 싶다.</p>
    </div>

    <br>
    {##}
    {#    <div style="padding-left: 600px; padding-right: 600px">#}
    {#        <div class="shadow-lg p-3 mb-5 bg-body rounded">#}
    {#            <div class="card" style="width: 18rem;">#}
    {#                <div class="card-body">#}
    {#                    <h5 class="card-title" style="text-align: center;">Get training</h5>#}
    {#                    <p class="card-text" style="text-align: center">.......</p>#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}


    <div class="col-md-6" style="margin-left: 400px;">
        <div class="card card-image mb-3"
             style="background-image: url('https://cdn57.androidauthority.net/wp-content/uploads/2018/01/machine-learning-algorithms-840x488.jpg');">
            <div class="text-white text-center d-flex align-items-center rgba-indigo-strong py-5 px-4">
                <div style="text-align: center; color: black;">
                    <h5 class="orange-text"><i class="fas fa-desktop"></i> intro</h5>
                    <h3 class="card-title pt-2"><strong>서비스 소개</strong></h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat fugiat, laboriosam,
                        voluptatem,
                    </p>
                </div>
            </div>
        </div>
        <div class="d-grid gap-2">
            <a href="{% url 'hello_world:upload' %}" class="btn btn-primary">let's start</a>
        </div>

    </div>



{% endblock %}

accountapp/templates/accountapp/test.html
{% extends 'base.html' %}

{% block content %}

    {% load static %}

{#        <video style="width: 700px; height:500px; margin-top: 50px; margin-left:400px; margin-right: auto;" src="{% static 'abc.mp4' %}" controls>#}
{#    <iframe width="320" height="180" src= frameborder="0" allowfullscreen=""#}
{#            style="position: absolute;  top: 0; left: 0; width: 100%; height: 100%;"></iframe>#}
    <iframe style="width: 500px; height:400px; margin-top: 50px; margin-left:500px; margin-right: auto;" src="https://www.youtube.com/embed/9W6VcNDWoGQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

{#    <iframe  src="https://youtu.be/9W6VcNDWoGQ"></iframe>#}




{% endblock %}

accountapp/templates/accountapp/upload.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


    <div style="padding-left: 600px; padding-right: 600px; padding-top: 200px;">
        <div class="shadow-lg p-3 mb-5 bg-body rounded">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title" style="text-align: center;">Get training</h5>
                    <form  action="{% url 'hello_world:test' %}"
                            method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="d-grid gap-2">
                            <input class="btn btn-light" type="file">
                            <input type="submit"  class="btn btn-dark" >
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<meta charset="utf-8">

<html>

{% load static %}

{% include 'head.html' %}
<body>

{% include 'header.html' %}



{% block content %}
{% endblock %}

</body>

</html>

{% include 'footer.html' %}

templates/footer.html
<style>
    .footer {

    position: absolute;
    left: 0;
    bottom: 0;
    width: 100%;
	padding-bottom: 0;
	text-align: center;
	color: white;
	background: black;

}

</style>

<footer>
    <div class="footer" style="font-weight: bold; text-align: center; ">
        <h6>From 임정박이 X KODE</h6>
    </div>
</footer>

templates/header.html
{% load static %}

<div style="padding: 30px; text-align: center;, cursive; background-color: white">
    <h1 style="color: blue; font-weight: bold">
            <img src="{% static 'parking2.png' %}" alt="" style="width: 70px; display: inline-block ">
            My Parking Space X  </h1>
    <br>
    <h3> 주차공간 실시간 정보 제공 서비스 </h3>
</div>